const Players = [
    {
        "name": "Agine Prosper",
        "age": 15,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713292025/talents/Agine_Prosper_lfnh2k.png",
        "mainPosition": "Midfield",
        "position": "CAM, CAM, CAM",
        "height": "",
        "weight": "53.4Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
        "nickname": "The Wall",
        "summary": "The Wall: A towering center-back known for his commanding presence in defense and aerial dominance. With a knack for timely tackles and clearances, he's a reliable anchor for any team's backline. Off the pitch, he's a dedicated student with a passion for strategy, aiming to pursue a professional career while representing Nigeria and dreaming of playing for Arsenal in the Premier League."
    },
    {
        "name": "Alexander Adodo",
        "age": 13,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713292025/talents/Alexander_Adodo_g1ibcz.png",
        "mainPosition": "Midfield",
        "position": "CAM",
        "height": "",
        "weight": "46.4Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "3668a7d2-d5d8-41c2-9f0e-8d7a2b3b5b3f",
        "nickname": "The Playmaker",
        "summary": "The Player Maker: A dynamic playmaker who orchestrates the flow of the game with his exceptional vision, passing range, and creativity. Whether threading pinpoint through balls or unleashing long-range strikes, he's the heartbeat of his team's attack. Despite his football prowess, he maintains a strong commitment to his studies, excelling academically. His dream is to represent Ghana at the highest level while gracing the midfield for Manchester United, his favorite Premier League club."
    },
    {
        "name": "Gideon Anaba",
        "age": 12,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713292025/talents/Gideon_Anaba_fhbv3h.png",
        "mainPosition": "Forward",
        "position": "CF,CAM",
        "height": "",
        "weight": "38.9Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "7a9fd7d2-0951-4f9e-b3d7-bdf9e986f9a4",
        "nickname": "The Goalscorer",
        "summary": "The Goal Scorer: A prolific goal-scorer blessed with blistering pace and deadly finishing skills. Whether it's cutting through defenses with speed or finding the back of the net with precision, he's a constant threat up front. Despite his prowess on the pitch, he maintains a strong focus on his studies, aiming to balance both worlds. His ultimate goal is to lead the line for Ghana at the highest level while wearing the jersey of Manchester City."
    },
    {
        "name": "Augustine Opoku",
        "age": 13,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034225/talents/Augustine_Opoku.png",
        "mainPosition": "Midfield",
        "position": "CDM",
        "height": "",
        "weight": "43.4Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "8c451f5d-84c0-4305-8102-84bc76f50de8",
        "nickname": "The Anchor"
    },
    {
        "name": "Beard Oppong",
        "age": 13,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034224/talents/Besard_Oppong.png",
        "mainPosition": "Midfield",
        "position": "CDM",
        "height": "",
        "weight": "42.2Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Left",
        "id": "abcc3f70-9731-4d85-8961-eafce5cb3dee",
        "nickname": "The Enforcer"
    },
    {
        "name": "Collins Boafo",
        "age": 10,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034224/talents/Collins_Boafo_ifvz39.png",
        "mainPosition": "Midfield",
        "position": "RWM",
        "height": "",
        "weight": "33.7Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "86988471-6f29-4fdd-99c5-96235e636263",
        "nickname": "The Speedster"
    },
    {
        "name": "Daniel Daossra",
        "age": 13,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034223/talents/Daniel_Daossra_fxep1c.png",
        "mainPosition": "Midfield",
        "position": "CAM",
        "height": "",
        "weight": "43.0Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "a96b5d06-7c29-4e07-8c18-7b897e7f1a09",
        "nickname": "The Maestro",
        "summary": "The Midfield Maestro: A versatile midfielder with exceptional vision and passing accuracy, capable of dictating the tempo of the game. His tactical awareness and ability to control the midfield make him a vital asset to any team. Balancing his football ambitions with academic excellence, he aspires to represent Ghana on the international stage and dreams of donning the colors of Liverpool in the English top flight."
    },
    {
        "name": "Denzel Adodo",
        "age": 12,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713292650/Denzel_Adodo_wneoi6.png",
        "mainPosition": "Forward",
        "position": "LWF",
        "height": "",
        "weight": "33.4Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Both",
        "id": "0d99be15-e291-4af5-9da3-c55ebd0eff7d",
        "nickname": "The Winger"
    },
    {
        "name": "Emmanuel Anaman",
        "age": 16,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713292022/talents/Emmanuel_Anaman_eqwtks.png",
        "mainPosition": "Goalkeeper",
        "position": "GK",
        "height": "",
        "weight": "46.4Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "68bba7a1-be4c-40f1-a226-477b7f3d1e90",
        "nickname": "The Shotstopper"
    },
    {
        "name": "Emmanuel Nyantekyi",
        "age": 13,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034223/talents/Emmanuel_Nyantekyi_s6raex.png",
        "mainPosition": "Defense",
        "position": "RB",
        "height": "",
        "weight": "33.9Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "9ddb44c1-012d-4e48-b727-5bf55eb84627",
        "nickname": "The Overlapper"
    },
    {
        "name": "Emmanuel Opoku",
        "age": 14,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034222/talents/Emmanuel_Opoku_s9mjca.png",
        "mainPosition": "Goalkeeper",
        "position": "GK",
        "height": "",
        "weight": "61.8Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "d2bc74d4-25fc-47de-8d8d-3c586ee0e1b1",
        "nickname": "The Giant"
    },
    {
        "name": "Enoch Ebenezer",
        "age": 14,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034221/talents/Enoch_Ebenezer_Mensah_gapadq.png",
        "mainPosition": "Defense",
        "position": "LB",
        "height": "",
        "weight": "44.4Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "7a2be9e2-f0a6-4818-ac6b-4e3e62c8d7b7",
        "nickname": "The Fullback"
    },
    {
        "name": "Francis Torgbor",
        "age": 13,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034221/talents/Francis_Torgbor_bfxs0n.png",
        "mainPosition": "Forward",
        "position": "CF",
        "height": "",
        "weight": "48.2Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "6d7b6c69-d3f0-4a9e-a4d6-b3b5f9c8d9a9",
        "nickname": "The Finisher"
    },
    {
        "name": "Gabriel Akavagre",
        "age": 11,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034221/talents/Gabriel_Akavagre_u4knuw.png",
        "mainPosition": "Defense",
        "position": "LB",
        "height": "",
        "weight": "33.4Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Both",
        "id": "a1f9c9d3-8f2d-4f9e-87c7-e8f9b7f8d7e4",
        "nickname": "The Youngster"
    },
    {
        "name": "Happy Okina",
        "age": 15,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713292020/talents/Happy_Okina_mtfzpl.png",
        "mainPosition": "Defense",
        "position": "CB",
        "height": "",
        "weight": "54.2Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "c7e59c9f-d7a8-4c5e-8c6f-e3d7b5d7e4f1",
        "nickname": "The Rock"
    },
    {
        "name": "Huzelfa Laryea",
        "age": 13,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034220/talents/Huzaifa_Laryea_yaoo7n.png",
        "mainPosition": "Midfield",
        "position": "CM",
        "height": "",
        "weight": "31.6Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "f8e6c7e2-f0e0-4d9e-a2c7-e8f9b7f8d7e4",
        "nickname": "The Workhorse"
    },
    {
        "name": "Isaac Agyekwa",
        "age": 16,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034221/talents/Isaac_Agyekwa_is7cqz.png",
        "mainPosition": "Midfield",
        "position": "CM",
        "height": "",
        "weight": "60.6Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "d2e7c9e2-f0e0-4d9e-a2c7-e8f9b7f8d7e4",
        "nickname": "The Engine"
    },
    {
        "name": "Isaac Osei",
        "age": 14,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034216/talents/Isaac_Osei_fhfkel.png",
        "mainPosition": "Defense",
        "position": "CB",
        "height": "",
        "weight": "47.2Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "a1f9c9d3-8f2d-4f9e-87c7-e8f9b7f8d7e4",
        "nickname": "The Stopper"
    },
    {
        "name": "Jacob Quartey",
        "age": 14,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713291765/talents/Jacob_Quartey_rwusss.png",
        "position": "LBW",
        "mainPosition": "Defense", 
        "height": "",
        "weight": "43.6Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "f8e6c7e2-f0e0-4d9e-a2c7-e8f9b7f8d7e4",
        "nickname": "The Wingman"
    },
    {
        "name": "John Tetteh",
        "age": 15,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034219/talents/John_Tetteh_yjr7b4.png",
        "position": "CAM,CM",
        "mainPosition": "Midfield",
        "height": "",
        "weight": "42.2Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Left",
        "id": "d2e7c9e2-f0e0-4d9e-a2c7-e8f9b7f8d7e4",
        "nickname": "The Technician"
    },

    {
        "name": "Junior Akuffour",
        "age": 10,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034218/talents/Junior_Akuffour_oxhhkh.png",
        "position": "RWF",
        "mainPosition": "Forward",
        "height": "",
        "weight": "30.8Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "a1f9c9d3-8f2d-4f9e-87c7-e8f9b7f8d7e4",
        "nickname": "The Youngster"
    },
    {
        "name": "Kingsley Mensah",
        "age": 16,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713291941/talents/Kingsley_Mensah_fgzgxj.png",
        "position": "RWF",
        "mainPosition": "Forward",
        "height": "",
        "weight": "57.6Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Left",
        "id": "f8e6c7e2-f0e0-4d9e-a2c7-e8f9b7f8d7e4",
        "nickname": "The Tricky Winger"
    },
    {
        "name": "Maxwell Ohene",
        "age": 14,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034218/talents/Maxwell_Ohene_zmlhaj.png",
        "position": "CMF",
        "mainPosition": "Midfield",
        "height": "",
        "weight": "49.5Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "d2e7c9e2-f0e0-4d9e-a2c7-e8f9b7f8d7e4",
        "nickname": "The Box-to-Box"
    },
    {
        "name": "Michael Tanu",
        "age": 10,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034218/talents/Michael_Tanu_vvn7kl.png",
        "position": "CAM",
        "mainPosition": "Midfield",
        "height": "",
        "weight": "33.9Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "a1f9c9d3-8f2d-4f9e-87c7-e8f9b7f8d7e4",
        "nickname": "The Little Maestro"
    },
    {
        "name": "Moro Ahmoah",
        "age": 9,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034218/talents/Moro_Ahmoah_hfwsqt.png",
        "position": "GK",
        "mainPosition": "Goalkeeper",
        "height": "",
        "weight": "24.1Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "f8e6c7e2-f0e0-4d9e-a2c7-e8f9b7f8d7e4",
        "nickname": "The Young Goalie"
    },
    {
        "name": "Nathaniel Quartey",
        "age": 15,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034217/talents/Nathaniel_Quartey_tu8y9n.png",
        "position": "CF",
        "mainPosition": "Forward",
        "height": "",
        "weight": "52.2Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Left",
        "id": "d2e7c9e2-f0e0-4d9e-a2c7-e8f9b7f8d7e4",
        "nickname": "The Marksman"
    },
    {
        "name": "Oscar Guarshie",
        "age": 13,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713291838/talents/Oscar_Guarshie_j0eenq.png",
        "position": "CB",
        "mainPosition": "Defense",
        "height": "",
        "weight": "35.4Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "a1f9c9d3-8f2d-4f9e-87c7-e8f9b7f8d7e4",
        "nickname": "The Warrior"
    },
    {
        "name": "Pascal Eshun",
        "age": 13,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713291794/talents/Pascal_Eshun_adjgfq.png",
        "position": "GK",
        "mainPosition": "Goalkeeper",
        "height": "",
        "weight": "56.3Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Both",
        "id": "f8e6c7e2-f0e0-4d9e-a2c7-e8f9b7f8d7e4",
        "nickname": "The Glove",
        "summary": "Very promising young goalie"
    },
    {
        "name": "Prince Fianku",
        "age": 11,
        "image": "https://res.cloudinary.com/broomstick/image/upload/t_spives_watermark/v1713034218/talents/Prince_Fianku_bkmahj.png",
        "position": "RWF",
        "mainPosition": "Forward",
        "height": "",
        "weight": "39.7Kg",
        "club": "Future Kids FC",
        "guardian": "",
        "coach": "Gideon",
        "foot": "Right",
        "id": "d2e7c9e2-f0e0-4d9e-a2c7-e8f9b7f8d7e4",
        "nickname": "The Flyer"
    },
].map(player => ({
    ...player,
    stats: {
        shooting: 0,
        speed: 0,
        passing: 0,
        dribbling: 0,
        overall: 0
    },
    country: "Ghana",
}));



export default Players;